services:
  mysql-shard-1:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    container_name: mysql-shard-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shardwallet1
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3307:3306"
    volumes:
      - shard1-data:/var/lib/mysql

  mysql-shard-2:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password   # ðŸ”¥ THIS WAS MISSING
    container_name: mysql-shard-2
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: shardwallet2
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10
    ports:
      - "3308:3306"
    volumes:
      - shard2-data:/var/lib/mysql

  wallet-service:
    build: .
    container_name: wallet-service
    depends_on:
      mysql-shard-1:
        condition: service_healthy
      mysql-shard-2:
        condition: service_healthy
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: docker

volumes:
  shard1-data:
  shard2-data:
